# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#/*
# * Copyright (c) 2017-2020 Seagate Technology LLC and/or its Affiliates
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *
# * For any questions about this software or licensing,
# * please email opensource@seagate.com or cortx-questions@seagate.com.
# *
# * Original author:  Ganesan Umanesan <ganesan.umanesan@seagate.com>
# * Original creation date: 10-Jan-2017
# *
# * Subsequent Modification: Abhishek Saha <abhishek.saha@seagate.com>
# * Modification Date: 02-Nov-2018
# *
# * Modification: Ganesan Umanesan <ganesan.umanesan@seagate.com>
# * Modification Date: 07-May-2020
# *
#*/

am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/cortx-motr-app
pkgincludedir = $(includedir)/cortx-motr-app
pkglibdir = $(libdir)/cortx-motr-app
pkglibexecdir = $(libexecdir)/cortx-motr-app
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
#IQUOTEDIR = /usr/include/motr
#M0GCCXML2XCODE = m0gccxml2xcode
#ifneq ($(M0_SRC_DIR),)
#am__append_1 = -L$(M0_SRC_DIR)/motr/.libs -Wl,-rpath=$(M0_SRC_DIR)/motr/.libs
#am__append_2 = -I$(M0_SRC_DIR) -I$(M0_SRC_DIR)/extra-libs/galois/include
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
SOURCES =
DIST_SOURCES =
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
am__DIST_COMMON = $(srcdir)/Makefile.in compile config.guess \
	config.sub install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps/missing autoconf
AUTOHEADER = ${SHELL} /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps/missing autoheader
AUTOMAKE = ${SHELL} /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps/missing automake-1.16
AWK = gawk
CC = gcc
CCDEPMODE = depmode=none
# generate .d dependencies automatically
CFLAGS = -I. -I/usr/include/motr -include config.h -D_REENTRANT \
	-D_GNU_SOURCE -DM0_INTERNAL='' -DM0_EXTERN=extern -fno-common \
	-Wall -Werror -Wno-attributes -fno-strict-aliasing -Wformat=0 \
	-fno-omit-frame-pointer -g -O2 -Wno-unused-but-set-variable \
	-rdynamic $(AM_FLAGS) -MP -MD $(am__append_2)
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"cortx-motr-app\" -DPACKAGE_TARNAME=\"cortx-motr-app\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"cortx-motr-app\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"cortx-motr-app\" -DVERSION=\"1.0\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
M0_CFLAGS = -pipe -Wall -Werror -Wno-attributes -fno-strict-aliasing -DPAGE_SIZE=4096 -DPAGE_SHIFT=12 
M0_SRC_DIR = 
MAKEINFO = ${SHELL} /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = cortx-motr-app
PACKAGE_BUGREPORT = 
PACKAGE_NAME = cortx-motr-app
PACKAGE_STRING = cortx-motr-app 1.0
PACKAGE_TARNAME = cortx-motr-app
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.0
abs_builddir = /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps
abs_srcdir = /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps
abs_top_builddir = /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps
abs_top_srcdir = /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/users/jusers/jena1/sage/pkg/new/clovis/new/cortx-motr-apps/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_FLAGS = -pipe -Wall -Werror -Wno-attributes -fno-strict-aliasing -DPAGE_SIZE=4096 -DPAGE_SHIFT=12 

#compiler/linker options
LFLAGS = -lm -lpthread -lrt -lyaml -luuid -lmotr $(am__append_1)

#sudo
SUDO = sudo

#files
FILE1 = './file1'
FILE2 = './file2'
FILE3 = './file3'

#executables
C0CP = c0cp
C0CT = c0cat
C0RM = c0rm
FGEN = fgen
RCDIR = $(HOME)/.c0appz
APPASSIGN = sage-user-application-assignment

#isc executables and library
LIBISC = libdemo.so
ISC_REG = c0isc_reg
ISC_INVK = c0isc_demo

#archive/node names
TARF = m0trace_$(shell date +%Y%m%d-%H%M%S).tar.bz2
TARN = $(shell ls -la m0trace.* &> /dev/null | wc -l)
NODE = $(shell eval uname -n)
IQUOTEDIR = /usr/include/motr
#IQUOTEDIR = $(M0_SRC_DIR)
M0GCCXML2XCODE = m0gccxml2xcode
#M0GCCXML2XCODE = $(M0_SRC_DIR)/xcode/m0gccxml2xcode
SRC = perf.o buffer.o qos.o c0appz.o dir.o list.o
SRC_ALL = $(SRC) c0cp.o c0cat.o c0rm.o fgen.o \
		c0isc_register.o c0isc_demo.o isc_libdemo.o


#dd block size, count and filesize
#dd can have any block size and a random
#number of blocks, making the file size
#random
DDZ = 1032
CNT = $(shell expr 100 + $$RANDOM % 1000)
#CNT = $(shell expr 1024 \* 16)
#CNT = 1024
FSZ = $(shell expr $(DDZ) \* $(CNT))

#c0cp block size
#valid block sizes are: 4KB ~ 32MB
#4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288,
#1048576, 2097152, 4194304, 8388608, 16777216, 33554432
BSZ = 64

#
#MPI Appz
#
MPIX = mpix
#CXXXML = gccxml

#ifneq ($(shell which castxml),)
#CXXXML := castxml
#CXXXML_FLAGS := --castxml-gccxml
#CXXXML_OUTPUT := -o # keep trailing blank-space after -o
#CXXXML2XC_FLAGS := --castxml
#else
#CXXXML := gccxml
CXXXML = castxml
# set maximum supported gcc version by gccxml, currently it's 4.2
#CXXXML_FLAGS = -DGCC_VERSION=4002 -DENABLE_GCCXML
CXXXML_FLAGS = --castxml-gccxml
#CXXXML_OUTPUT = -fxml=
CXXXML_OUTPUT = -o # keep trailing blank-space after -o
#CXXXML2XC_FLAGS = 
CXXXML2XC_FLAGS = --castxml
CXXXML_UNSUPPORTED_CFLAGS = -Wno-portability  -Wno-unused-but-set-variable -Werror -Wno-trampolines -rdynamic --coverage -pipe -Wp,-D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -grecord-gcc-switches -fstack-protector-strong -fstack-clash-protection -MD -MP -include config.h
CXXXML_CFLAGS = $(filter-out $(CXXXML_UNSUPPORTED_CFLAGS), $(CFLAGS))
all: all-am

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
tags TAGS:

ctags CTAGS:

cscope cscopelist:


distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile
installdirs:
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-local mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-exec-local

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-local

.MAKE: install-am install-strip

.PHONY: all all-am am--refresh check check-am clean clean-generic \
	clean-local cscopelist-am ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-generic distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-exec-local \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic pdf pdf-am ps ps-am tags-am \
	uninstall uninstall-am uninstall-local

.PRECIOUS: Makefile

#or not
undefine SUDO

all: $(C0CP) $(C0CT) $(C0RM) $(FGEN) isc-all
.PHONY: all

-include $(SRC_ALL:.o=.d)

%.o: %.c
	gcc -c $(CFLAGS) -o $@ $<

$(C0CP): c0cp.c $(SRC)
	gcc $(CFLAGS) $(LFLAGS) $(SRC) -o $@ $<

$(C0CT): c0cat.c $(SRC)
	gcc $(CFLAGS) $(LFLAGS) $(SRC) -o $@ $<

$(C0RM): c0rm.c $(SRC)
	gcc $(CFLAGS) $(LFLAGS) $(SRC) -o $@ $<

$(FGEN):
	gcc -lssl -lcrypto fgen.c -o $(FGEN)

test: $(C0CP) $(C0CT) $(C0RM) $(FGEN)
	$(eval FID1 := $(shell eval ./$(FGEN)))
	$(eval FID2 := $(shell eval ./$(FGEN)))

	$(SUDO) dd if=/dev/urandom of=$(FILE1) bs=$(DDZ) count=$(CNT)
	@echo "#####"
	@ls -lh $(FILE1)
	@echo "#####"
	$(SUDO) ./$(C0RM) $(FID1) -y
	sleep 1
	$(SUDO) ./$(C0RM) $(FID2) -y
	sleep 1
	@echo "#####"
	$(SUDO) ./$(C0CP) $(FID1) $(FILE1) $(BSZ) -p
	@echo "#####"
	@ls -la $(FILE1)
	$(SUDO) ./$(C0CT) $(FID1) $(FILE2) $(BSZ) $(FSZ) -p
	@ls -la $(FILE2)
	@echo "#####"
	@ls -la $(FILE1)
	$(SUDO) ./$(C0CP) $(FID2) $(FILE1) $(BSZ) -a 8 -p
	@echo "#####"
	$(SUDO) ./$(C0CT) $(FID2) $(FILE3) $(BSZ) $(FSZ) -p
	@ls -ls $(FILE3)
	@echo "#####"
	cmp $(FILE1) $(FILE2) || echo "ERROR: Test Failed !!"
	@echo "#####"
	cmp $(FILE1) $(FILE3) || echo "ERROR: Async Test Failed !!"
	@echo "#####"
	$(SUDO) ./$(C0RM) $(FID1) -y
	sleep 1
	$(SUDO) ./$(C0RM) $(FID2) -y

#yaml
#bundle trace files for shipment
yaml:
	@ls m0trace.* &> /dev/null || (echo "No traces!" && exit 1)
	@for file in m0trace.*; do						\
		echo $$file;							\
	ls -lh $$file;								\
		m0trace -Y -i $$file -o $$file.yml;				\
		ls -lh $$file.yml;						\
	done
	tar -jcvf $(TARF) m0trace.*.yml
	tar -jtvf $(TARF)
	rm -f m0trace.*.yml
	ls -lh $(TARF)

vmrcf:
	mkdir -p $(RCDIR)/${C0CP}rc
	mkdir -p $(RCDIR)/${C0CT}rc
	mkdir -p $(RCDIR)/${C0RM}rc
	mkdir -p $(RCDIR)/$(ISC_REG)rc
	mkdir -p $(RCDIR)/$(ISC_INVK)rc
	./scripts/c0appzrcgen > $(RCDIR)/$(C0CP)rc/$(NODE)
	./scripts/c0appzrcgen > $(RCDIR)/$(C0CT)rc/$(NODE)
	./scripts/c0appzrcgen > $(RCDIR)/$(C0RM)rc/$(NODE)
	./scripts/c0appzrcgen > $(RCDIR)/$(ISC_REG)rc/$(NODE)
	./scripts/c0appzrcgen > $(RCDIR)/$(ISC_INVK)rc/$(NODE)

sagercf:
	mkdir -p $(RCDIR)/${C0CP}rc
	mkdir -p $(RCDIR)/${C0CT}rc
	mkdir -p $(RCDIR)/${C0RM}rc
	mkdir -p $(RCDIR)/$(ISC_REG)rc
	mkdir -p $(RCDIR)/$(ISC_INVK)rc
	HOSTNAME=$(NODE) ./scripts/motraddr.sh > out-$(HOSTNAME).txt
	@echo "#####"
	cat ./out-$(HOSTNAME).txt
	@echo "#####"
	cp out-$(HOSTNAME).txt $(RCDIR)/$(C0CP)rc/$(NODE)
	cp out-$(HOSTNAME).txt $(RCDIR)/$(C0CT)rc/$(NODE)
	cp out-$(HOSTNAME).txt $(RCDIR)/$(C0RM)rc/$(NODE)
	cp out-$(HOSTNAME).txt $(RCDIR)/$(ISC_REG)rc/$(NODE)
	cp out-$(HOSTNAME).txt $(RCDIR)/$(ISC_INVK)rc/$(NODE)
	rm -rf out-$(HOSTNAME).txt

install-exec-local:
	mkdir -p $(HOME)/bin
	cp $(C0CP) $(HOME)/bin/
	cp $(C0CT) $(HOME)/bin/
	cp $(C0RM) $(HOME)/bin/
	cp $(FGEN) $(HOME)/bin/

uninstall-local:
	rm $(HOME)/bin/$(C0CP)
	rm $(HOME)/bin/$(C0CT)
	rm $(HOME)/bin/$(C0RM)
	rm $(HOME)/bin/$(FGEN)
	rmdir -p $(HOME)/bin

clean-local: isc-clean
	rm -f $(C0CP) $(C0CT) $(C0RM) m0trace.*
	rm -f $(FILE1) $(FILE2) $(FILE3)
	rm -f $(FGEN)
	rm -f sfilet-* snodet-* fidout-*
	rm -f upFile dwFile
	rm -f *.o *.d *.d.* help.h

m0t1fs:
	touch /mnt/m0t1fs/0:3000
	setfattr -n lid -v 8 /mnt/m0t1fs/0:3000
	dd if=/dev/zero of=/mnt/m0t1fs/0:3000 bs=4M count=10
	ls -lh /mnt/m0t1fs/0:3000
	rm -rf /mnt/m0t1fs/0:3000

bigtest:
	make
	make fgen
	touch ./.fgenrc
	./scripts/single_node_test 4096 1024*1   1
	./scripts/single_node_test 4096 1024*2   1
	./scripts/single_node_test 4096 1024*4   1
	./scripts/single_node_test 4096 1024*8   1
	./scripts/single_node_test 4096 1024*16  1
	./scripts/single_node_test 4096 1024*32  1
	./scripts/single_node_test 4096 1024*64  1
	./scripts/single_node_test 4096 1024*128 1
	./scripts/single_node_test 4096 1024*256 1
	./scripts/single_node_test 4096 1024*512 1

$(MPIX): $(SRC) mpiapp.c
	mpicc $(SRC) mpiapp.c -I/usr/include/motr $(CFLAGS) $(LFLAGS) -o $(MPIX)

mpi-clean:
	rm -f *.o *.d *.d.*
	rm -f m0trace.*
	rm -f $(MPIX)

mpi-sagercf:
	mkdir -p $(RCDIR)/${MPIX}rc
	HOSTNAME=$(NODE) ./scripts/motraddr.sh 2 > out-$(HOSTNAME).txt
	@echo "#####"
	cat ./out-$(HOSTNAME).txt
	@echo "#####"
	cp out-$(HOSTNAME).txt $(RCDIR)/$(MPIX)rc/$(NODE)
	rm -rf out-$(HOSTNAME).txt

mpi-test:
	mpirun -hosts $(NODE) -np 2 ./$(MPIX)

#
#ISC Demo
#Sage Function Shipping
#

$(ISC_REG): c0isc_register.o $(SRC)
	gcc $(LFLAGS) $(SRC) -o $@ $<

$(LIBISC): isc_libdemo.c isc/libdemo_xc.c
	gcc $(CFLAGS) -fpic -shared -o $@ isc/libdemo_xc.c $<

$(ISC_INVK): c0isc_demo.o isc/libdemo_xc.o $(SRC)
	gcc $(LFLAGS) $(SRC) isc/libdemo_xc.o -o $@ $<

c0isc_demo.c: isc/libdemo_xc.h

%_xc.h %_xc.c: %.h
	$(CXXXML) $(CXXXML_FLAGS) $(CXXXML_CFLAGS) $(CXXXML_OUTPUT)$(<:.h=.gccxml) $<
	$(M0GCCXML2XCODE) $(CXXXML2XC_FLAGS) -i $(<:.h=.gccxml)

isc-all: $(ISC_REG) $(ISC_INVK) $(LIBISC)
isc-clean:
	rm -f $(ISC_REG) $(ISC_INVK) $(LIBISC) isc/{*_xc.*,*.gccxml}

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
